In [13]:
import os
import pandas as pd

In [14]:
BASE_DIR = os.getcwd()
PROJECT_ROOT = os.path.dirname(BASE_DIR)
DATA_PATH = os.path.join(PROJECT_ROOT, "data", "ultimate_student_productivity_dataset_5000.csv")

In [15]:
df = pd.read_csv(DATA_PATH)
df.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   str
 3   academic_level        5000 non-null   str
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   int64
 14  upcoming_deadline     5000 non-null   int64
 15  internet_quality      5000 non-null   str
 16  mental_health_score   5000 non-null   int64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(11), int64(7), str(3)
memory usage: 820.4 KB

In [17]:
df['gender'].value_counts()

gender
Male      1719
Other     1651
Female    1630
Name: count, dtype: int64

In [18]:
df['academic_level'].value_counts()

academic_level
Postgraduate     1687
High School      1672
Undergraduate    1641
Name: count, dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
cat_cols = df.select_dtypes(include='str').columns

for col in cat_cols:
    df[col] = lb.fit_transform(df[col])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   int64
 3   academic_level        5000 non-null   int64
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   int64
 14  upcoming_deadline     5000 non-null   int64
 15  internet_quality      5000 non-null   int64
 16  mental_health_score   5000 non-null   int64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(11), int64(10)
memory usage: 820.4 KB

In [20]:
df.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,2,0,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,1,10,43.05,31.77,73.65,50.16
1,2,18,2,0,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,1,3,15.92,37.00,13.70,1.00
2,3,22,1,0,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,1,8,27.39,34.37,45.15,18.30
3,4,17,2,0,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,2,3,22.31,77.31,20.92,9.37
4,5,19,2,0,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,1,8,38.11,39.53,59.23,27.81

In [21]:
df.isnull().sum()

student_id              0
age                     0
gender                  0
academic_level          0
study_hours             0
self_study_hours        0
online_classes_hours    0
social_media_hours      0
gaming_hours            0
sleep_hours             0
screen_time_hours       0
exercise_minutes        0
caffeine_intake_mg      0
part_time_job           0
upcoming_deadline       0
internet_quality        0
mental_health_score     0
focus_index             0
burnout_level           0
productivity_score      0
exam_score              0
dtype: int64

In [22]:
SAVE_PATH = os.path.join(PROJECT_ROOT, "data", 'preprocessed.csv')
df.to_csv(SAVE_PATH, index=False)